basePath: /
definitions:
  models.Account:
    properties:
      created_at:
        type: integer
      document_number:
        type: integer
      id:
        type: integer
      updated_id:
        type: integer
    type: object
  models.Transaction:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      created_at:
        type: integer
      id:
        type: integer
      operation_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: thiago.zilli@gmail.com
    name: API Support
    url: https://thiagozs.com
  description: Simple documentation of API.
  license:
    name: Reserved Commons
    url: https://thiagozs.com/license
  termsOfService: https://thiagozs.com/terms/
  title: Codding challenge
  version: "2.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: This method you will create a new Account
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
      summary: Create a new Account
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: Get a JSON with search by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Account'
      summary: Get information about accounts
  /transactions:
    post:
      consumes:
      - application/json
      description: This method you will create a new transaction
      parameters:
      - description: Transaction
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Account'
      summary: Create a new Account
  /transactions/account/{id}:
    get:
      consumes:
      - application/json
      description: Get a JSON with search by ID
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transaction'
            type: array
      summary: Get information about transactions by account ID
schemes:
- http
swagger: "2.0"
